[window]
decorations = "None"
opacity = 0.85
startup_mode = "Maximized"
resize_increments = true 
blur = true
[font]
normal = {family ="CascadiaCode NF" }
bold = {family ="CascadiaCode NF"}
italic = {family ="CascadiaCode NF"}
bold_italic = {family ="CascadiaCode NF"}
# normal = {family ="Comic Shanns Mono"}
# bold = {family ="Comic Shanns Mono"}
# italic = {family ="Comic Shanns Mono"}
# bold_italic = {family ="Comic Shanns Mono"}
size = 16.5
[mouse]
hide_when_typing = true
[env]
TERM = "xterm-256color"

[general]
import= ["~/.config/alacritty/color.toml"]
