import= ["~/.config/alacritty/color.toml"]
[window]
decorations = "None"
opacity = 1
startup_mode = "Maximized"
resize_increments = true 
blur = true
[font]
normal = {family ="Maple Mono NF"}
bold = {family ="Maple Mono NF"}
italic = {family ="Maple Mono NF"}
bold_italic = {family ="Maple Mono NF"}
size = 20
[mouse]
hide_when_typing = true
[env]
TERM = "xterm-256color"
