import= ["~/.config/alacritty/color.toml"]
[window]
decorations = "None"
opacity = 0.8
startup_mode = "Maximized"
resize_increments = true 
blur = true
[font]
normal = {family ="Cascadia Code NF"}
bold = {family ="Cascadia Code NF"}
italic = {family ="Cascadia Code NF"}
bold_italic = {family ="Cascadia Code NF"}
size = 15
[mouse]
hide_when_typing = true
[env]
TERM = "xterm-256color"
